[package]
name = "localbridge-desktop"
version = "1.20.0"
description = "Nexus Desktop Control Center"
authors = ["Nexus Team"]
edition = "2021"
license = "Apache-2.0"

[package.metadata.tauri-winres]
OriginalFilename = "localbridge-desktop.exe"
InternalName = "Nexus Control Center"
FileDescription = "Nexus"
ProductName = "Nexus"
CompanyName = "Nexus"
LegalCopyright = "Copyright © 2026 Nexus"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "image-ico"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
getrandom = "0.3"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true
